### ISSUE TITLE
Awfully innacurate results due to lack of gamma correction when scaling

### ISSUE THREAD

**Issue by kdrnic** [mlaily/MovieBarCodeGenerator#3]
Your generator clearly does some operations in the incorrect colour space.
This has significant results, specially in darkening the resulting images.
Here is a test file I've built:

1. With GIMP, I made 7 checkerboard patterns, one in each layer, each with two colours, (white/black, red/green, blue/green, blue/red, blue/yellow, green/magenta, cyan/red). Those colours should average out, if correctly scaled, to grey, yellow, cyan, magenta, grey, grey, and grey, respectively, at 50% intensity
2. I exported this as an animated GIF file, with 1s (1000ms) for each layer
3. I converted this GIF file to a .mp4 file with 'ffmpeg -i avgColourTest.gif avgColourTest.mp4'
4. Then I ran the generator on the mp4 file

Here I have attached the files mentioned above, for your convenience:
[avgColourTest.zip](https://github.com/mlaily/MovieBarCodeGenerator/files/5685713/avgColourTest.zip)

Unfortunately, the generated barcode is too dark, and I note the generated grey (as well as the yellow/cyan/magenta) has its RGB components at 128 - this clearly tells the scaling/averaging of values is done without considering gamma, i.e. in the incorrect colour space. A grey of 50% intensity has RGB values of 186 instead.

Below, I contrast the resulting barcode with the expected colours:

![MovieBarcodeGen1500avgColourTestLabelled](https://user-images.githubusercontent.com/7352278/102027109-d6930680-3d80-11eb-9044-ce9930402d38.png)

Here are two links to great articles about this common issue in image processing:
[What every coder should know about gamma](https://blog.johnnovak.net/2016/09/21/what-every-coder-should-know-about-gamma/)
[Gamma error in picture scaling](http://www.ericbrasseur.org/gamma.html?i=1)

**Comment by mlaily** [comment]
Ha! Thanks for this thorough bug report. I remember reading your first article some years ago :)

I would argue that the bug is in [GDI+ and not in my code](https://github.com/mlaily/MovieBarCodeGenerator/blob/master/MovieBarCodeGenerator/Core/ImageProcessor.cs#L68), but I will see what I can do (From a quick look, either I stop using GDI+, or I do the gamma correction myself...)

**Comment by mlaily** [comment]
This has been fixed in the latest 2.0 release!

Before:
![avgColourTest_legacy](https://user-images.githubusercontent.com/1535823/105252238-5fba0c00-5b7d-11eb-88c0-cb4bc8fe3253.png)
Now:
![avgColourTest](https://user-images.githubusercontent.com/1535823/105252237-5f217580-5b7d-11eb-9b0d-5ea8979d5fc0.png)
